### ISSUE TITLE
MEPS dataset issue - no .csv files

### ISSUE THREAD

**Issue by kai-wren** [Trusted-AI/AIF360#222]
For version 0.3.0 when reading MEPS dataset no .csv files found under the path specified below.

Code:
(dataset_orig_panel19_train,
 dataset_orig_panel19_val,
 dataset_orig_panel19_test) = MEPSDataset19().split([0.5, 0.8], shuffle=True)

Result:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/aif360/datasets/../data/raw/meps/h181.csv'
To use this class, please follow the instructions in:

	/usr/local/lib/python3.6/dist-packages/aif360/data/raw/meps/README.md

 to download and convert the 2015 data and place the final h181.csv file, as-is, in the folder:

	/usr/local/lib/python3.6/dist-packages/aif360/data/raw/meps

An exception has occurred, use %tb to see the full traceback.

I checked in the filesystem - files indeed missing. When I used version 0.2.3 files are there. When I upgraded it to version 0.3.0 - the files are gone. I did a check using google Colab.

**Comment by hoffmansc** [comment]
Please see the [instructions](https://github.com/Trusted-AI/AIF360/tree/master/aif360/data/raw/meps) here to download the dataset. Due to licensing issues, we do not distribute the datasets with the AIF360 package, however, there is a script in that folder which automates the process if you accept the terms.

**Comment by nrkarthikeyan** [comment]
This is expected, so closing.
