### ISSUE TITLE
Version reconciliation with AIX360

### ISSUE THREAD

**Issue by forbug** [Trusted-AI/AIF360#297]
My team is working on a repository (https://github.ibm.com/ML-Pipelines/ml-pipelines) to demonstrate code examples used across IBM. We are using poetry environments to compartmentalize our environments.

We have tried many python versions (3.7.0, 3.7.1, 3.7.4, 3.9.6) for our environment that demonstrates IBM Research Trusted-AI code, but none of them have allowed us to install both AIX360 (>=3.6) and AIF360 (>=3.7) without install errors.

Would you recommend any Python version (or any other environment configurations) to get these to work together?

**Comment by evaline-ju** [comment]
My IBM team is working on a way to reconcile some of these algorithms from the various Trusted-AI research toolkits. Since your team's work seems to also be IBM-internal or at least in an internal repository, I'll reach out separately to discuss how we may potentially collaborate to solve some of these issues.

**Comment by nrkarthikeyan** [comment]
Closing since this discussion will happen elsewhere.
