### ISSUE TITLE
Request for New Release Compatible with Latest Numpy Version

### ISSUE THREAD

**Issue by ZanMervic** [Trusted-AI/AIF360#500]
Hello aif360 maintainers,

I recently encountered an issue with the aif360 library (version 0.5.0) being incompatible with the latest release of numpy. Upon investigating, I found that the main branch of aif360 already has a fix in place for this compatibility issue.

For the benefit of everyone who might be facing similar issues, I kindly request that you consider making a new release of aif360 that includes this fix. This will allow us to use the aif360 library seamlessly with the latest version of numpy.

Thank you for your time and consideration. I understand the constraints and challenges involved in maintaining a library, and I genuinely appreciate any effort you can make in this regard.

Best regards,
ZanMervic

**Comment by PrimozGodec** [comment]
@hoffmansc, any news on this one. It would be really helpful to have aif360 compatible with the newest Numpys. 1.23 is quite old already.

**Comment by PrimozGodec** [comment]
@hoffmansc, can a new release be made, please? It is really necessary because of the Numpy fix. For example it is blocking https://github.com/conda-forge/staged-recipes/pull/24166/files/9728bbcf193456805bf2f66340c967c5e1929cab..8401cdbfc7e4ffc501114cea6cadfe5c1e63f633

**Comment by PrimozGodec** [comment]
@hoffmansc, any news on the new release. :)

**Comment by PrimozGodec** [comment]
@hoffmansc, I would kindly ask for a new release because it is blocking other PRs (see comments above). If you need any help with the release, please let me know.

**Comment by PrimozGodec** [comment]
@hoffmansc, is there any news on the release? We would need it since our package orange3-fairness cannot make it to the conda-forge https://github.com/conda-forge/staged-recipes/pull/24166/files/9728bbcf193456805bf2f66340c967c5e1929cab..8401cdbfc7e4ffc501114cea6cadfe5c1e63f633

The release will fix the situation.

**Comment by PrimozGodec** [comment]
@hoffmansc, is there any news on the release? We would need it since our package orange3-fairness cannot make it to the conda-forge https://github.com/conda-forge/staged-recipes/pull/24166/files/9728bbcf193456805bf2f66340c967c5e1929cab..8401cdbfc7e4ffc501114cea6cadfe5c1e63f633

The release will fix the situation.

**Comment by hoffmansc** [comment]
This is finally done. Apologies for the lengthy delay.
